name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy_application:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: install dependencies
        run: npm install
      - name: lint and format
        run: npm run format
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: heroku deploy
        if: ${{ github.event_name == 'push' }} 
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "stockroom-boss"
          heroku_email: "git.kholston@gmail.com"
          healthcheck: "https://stockroom-boss.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          
